spring:
  application:
    name: currency-consumer
    instance_id: ${random.value}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

target_service: currency-provider
schedule:
  delay: PT5S