spring:
  application:
    name: currency-provider
    instance_id: ${random.value}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

currency: 100